### PR TITLE
Add Agregore Demos Open Grant Proposal

### PR DESCRIPTION
**Pull request by RangerMauve**
Hey folks,

This was developed after talking with @autonome on progressing IPFS and P2P web stuff as a follow on to the [Agregore Mobile](https://github.com/ipfs/devgrants/pull/129) grant.

This time we'll be building on the existing handlers to provide usable p2p web apps with IPFS as well as tutorials others can follow to create their own versions.

Finally, this is going to be an effort to find pain points in IPFS protocol handlers which we can use to make fixes and make onboarding easier.

### CODE REVIEW

**Comment by RangerMauve** [comment]
Hey, I was wondering if there was any ETA on when this could be reviewed. 😁

**Comment by ErinOCon** [comment]
HI @RangerMauve, thank you for your proposal and for your patience with our review! I have just sent you an email to discuss next steps.

**Comment by RangerMauve** [comment]
We got all the contracts signed and are getting started on this in full force this week. 😁 We're going to aim to have milestone 1 done by the beginning of January.

**Comment by RangerMauve** [comment]
Folks can follow our project board tracking our progress here: https://github.com/orgs/AgregoreWeb/projects/3

**Comment by RangerMauve** [comment]
We're ready to have milestone 1 reviewed.

We've published our announcement blog post here: https://agregore.mauve.moe/blog/2023/01/demos-and-tutorials-announcement

And have got the process we'll be taking for our app/tutorial milestones documented here: https://agregore.mauve.moe/docs/tutorials/process

**Comment by RangerMauve** [comment]
Sent out the invoice for milestone 1 :)

**Comment by RangerMauve** [comment]
Hey, we're ready to have milesone 2 reviewed. The blog post with our outcomes can be found here: https://agregore.mauve.moe/blog/2023/07/demos-and-tutorials-first-round

Links to the demos and tutorials can be found there.

cc @autonome ready for review when you have time

**Comment by autonome** [comment]
Did a review pass here, mostly link and content fixes:

https://github.com/AgregoreWeb/website/pull/40#issuecomment-1668091843

**Comment by autonome** [comment]
Reviewed the submitted changes, and approved milestone 2 as complete 👍🏼👍🏼👍🏼

**Comment by RangerMauve** [comment]
Ready to have milestone 3 reviewed.

Deliverables:
- 0-3 web apps on website
  - [p2p chat app](https://agregore.mauve.moe/docs/examples/ipfs-pub-sub-chat/)
  - [directory uploader](https://agregore.mauve.moe/docs/examples/browser-devenv-2/)
  - [drag and drop](https://agregore.mauve.moe/docs/examples/drag-and-drop/)
- 0-3 tutorials
  - [pubsub tutorial](https://agregore.mauve.moe/docs/tutorials/ipfs-pub-sub-chat)
  - [directory uploader tutorial](https://agregore.mauve.moe/docs/tutorials/ipfs-dir-upload/)
  - [drag and drop tutorial](https://agregore.mauve.moe/docs/tutorials/drag-and-drop)
- 3 retrospectives
  - [pub sub chat retro](https://agregore.mauve.moe/blog/2023/11/ipfs-pub-sub-chat-retro)
  - [directory uploader retro](https://agregore.mauve.moe/blog/2023/12/ipfs-dir-upload-retrospective)
  - [drag and drop retro](https://agregore.mauve.moe/blog/2023/11/drag-and-drop-retrospective)
- [blog post](https://agregore.mauve.moe/blog/2023/12/demos-and-tutorials-second-round#webapps-milestone-3)

Bonus: Vincent added some more [docs](https://agregore.mauve.moe/docs/hypercore-protocol-handlers)

**Comment by autonome** [comment]
There are a few minor things noted below that would be great to see cleaned up, and I haven't finished a real "in the wild" test of the chat app, but looking great so far. Marked things needing fixes or testing below with 🛠️.

General notes:
- Very cool that some of this builds on the editor from the first round
- I really appreciate the continual focus on simple+vanilla code, reduced to absolute minimum
- Overall these are great balance of useful basics and hands-on training for beginners

Pubsub chat app
- 🛠️ I am finding someone to test with me for >1 user

Directory uploader
- 🛠️ The upload editor goes back to start page after uploading files which is confusing. it did in fact work correctly as the files showed up, but would be great to see this behavior fixed
- Publishing the site didn't work afaict? nothing happened after waiting quite a while - but that's not the point of this particular tutorial, so nbd, just noting it
- 🛠️ The conclusion in the retro looks like not finished.

Drag and drop uploader
- App worked as expected, and hyper worked too, very cool
- "First, we define a function to simplify document.querySelector" ahaha, it me

**Comment by autonome** [comment]
Testing confirmed for the chat app. Approved from technical delivery standpoint, one the other fixes above are done by the team.

**Comment by RangerMauve** [comment]
Ready to have milestone 4 reviewed.

Deliverables:
- 4 web apps on website
  - [ace editor](https://agregore.mauve.moe/docs/examples/browser-devenv-v3/index.html)
  - [image gallary](https://agregore.mauve.moe/docs/examples/ipfs-gallery/)
  - [p2pad](https://agregore.mauve.moe/docs/examples/p2pad/)
  - [liink tree](https://agregore.mauve.moe/docs/examples/dlinktree-builder/)
- 4 tutorials
  - [ace editor](https://agregore.mauve.moe/docs/tutorials/ipfs-3rdparty-dep/)
  - [image gallary](https://agregore.mauve.moe/docs/tutorials/ipfs-gallery/)
  - [p2pad](https://agregore.mauve.moe/docs/tutorials/p2pad-code-editor)
  - [link tree](https://agregore.mauve.moe/docs/tutorials/dlinktree-builder)
- 4 retrospectives
  - [Ace Editor](https://agregore.mauve.moe/blog/2024/01/ipfs-3rd-party-dep-retrospective)
  - [IPFS Gallary](https://agregore.mauve.moe/blog/2024/03/ipfs-gallery-retrospective)
  - [P2Pad](https://agregore.mauve.moe/blog/2024/01/p2pad-code-editor-retrospective)
  - [DLinkTree](https://agregore.mauve.moe/blog/2024/03/dlinktree-builder-retrospective)
- [blog post](hyper://agregore.mauve.moe/blog/2024/03/demos-and-tutorials-final-round)

**Comment by autonome** [comment]
oh, i tested in Agregore 2.5.0

**Comment by RangerMauve** [comment]
Oh! The style issue is a bug in agregore. I'll make a fix tomorrow.

**Comment by RangerMauve** [comment]
@autonome Mind posting a screenshot of the gallary bottom bar being out of view? I am having trouble reproducing it. What OS are you on? Also how wide is your window?

I am also having trouble reproducing the issue with p2pad. It feels like it could be a mac OS issue which I thought I fixed in the past.

**Comment by RangerMauve** [comment]
@autonome Fixed the linking issues, fixed the style issue, released a new version of Agregore that fixes the issue with the content being pushed out of the viewport (good catch!).

https://github.com/AgregoreWeb/agregore-browser/releases/tag/v2.5.1

**Comment by autonome** [comment]
Rad, updated and tested w/ 2.5.1. All previously reported issues fixed. Now can review the gallery and p2pad tutorials.

Gallery is all good.

P2pad:
- in step 4, the link to the dnd tutorial is 404
- should add a link to the final working version, like the other tutorials have

Aside from those last two bits, technical/content review is concluded and m4 is approved from my end.

**Comment by RangerMauve** [comment]
@autonome Fixed! https://github.com/AgregoreWeb/website/pull/60

**Pull request merged**
