### PR TITLE
Add open-proposal-ipld-prolly-trees

### PR DESCRIPTION
**Pull request by RangerMauve**
Hello,

Here's a PR for a devgrant we'd like to pursue for standardizing B tree based indexes in the IPLD ecosystem.

This was put together with the help of @autonome and folks in the IPFS ecosystem like @mikeal 

cc @kenlabs

### CODE REVIEW

**Comment by warpfork** [comment]
Holistic: YES.

We need more support for big maps in the IPLD ecosystem.  This proposal will accomplish that.

The most commonly discussed "big map" ADL currently in our ecosystem is the HAMT.  HAMTs are very lovely, but they have two weaknesses:

- They're not ordered!  (This means they're approximately useless for indexing purposes.)
- In practice... we didn't standardize them particularly well, and we have many minor variations of them floating around in the wild.  (Not a problem!  But not ideal, either -- our experience with how much "extra" this "costs" vs value provided by the variation should give us good reason to encourage standardization and test vectors (!!) for future endeavors.)

The approach proposed here will support ordered big maps, which will provide value that HAMTs do not currently provide.  Also, if there is success in standardizing and publishing lots of test vectors in such a way that future developments can converge better, I'll be very happy with that as a bonus win.

Equally critically, the proposed data structures still have the property of being ahistoric -- in other words, the history of insertions and deletions doesn't matter to the sharding state reached at any point in time -- meaning they converge! -- which means these structures are on approximately equal footing with HAMTs in the convergence property.  (We care about converge properties for deduplication outcomes, but also out of sheer general principle in decentralization: it tends to have myriad simplifying effects that can affect higher levels of protocol in drastically positive ways.)

In total, implementing these data structures should provide new value in areas that we don't already have covered.  :+1: :+1: :+1:

---

I'm less familiar with the hyperbeedeebee part, and haven't reviewed that system deeply, but at first glance, I don't think I have any objections to it, directionally: so, sure.  (I'm totally happy with how the indexing part is layered in this proposal separately from the core datastructure parts!  That means I don't even have to buy in to hyperbeedeebee in order for the proposal to be good overall.  At worst, hyperbeedeebee still serves as a "pull forward" sort of goal, which will help move the lower level work forward.  At best, it becomes awesome on its own.  Even the "at worst" outcome is good!)

**Comment by RangerMauve** [comment]
Just wondering if there was any sort of ETA on the FIL team for reviewing this. It'd be nice to get to present it at the IPFS thing next week. 😁

**Comment by ErinOCon** [comment]
Hi @RangerMauve, this grant has been approved! We will follow up with an email to discuss next steps.

**Comment by RangerMauve** [comment]
Awesome, thank you! 🎉

**Comment by RangerMauve** [comment]
Hey! We've finished up Milestone 1.

We've got the initial version of the spec ready in https://github.com/ipld/ipld/pull/254/ We also have links to our research materials there.

Our MVP is here: https://github.com/kenlabs/ptree-bs/pulls as well as the initial fixtures we made.

We will be doing the ADL implementation in the next. We'll also be generating new fixtures as part of that.

**Comment by RangerMauve** [comment]
Hey, tried to send the invoice for Milestone 1 in December and haven't heard anything back.

Is there a better place to reach folks on the finance team or some sort of ETA?

**Comment by ErinOCon** [comment]
Hi @RangerMauve, this invoice is being processed. Just sent you an email!

**Comment by RangerMauve** [comment]
Hey folks, we're ready for a review of our next milestone (milestone 3).

Our repo for the indexer is here: https://github.com/RangerMauve/ipld-prolly-indexer/

**Comment by autonome** [comment]
Discussed, and @RangerMauve and team will make a nice table for us to see which part of team is doing which milestone, which is completed, has invoice in process, etc.

**Comment by RangerMauve** [comment]
Hey there, I finally had a chance to review our two tracks (R: research, D: Development) and set up this table tracking progress:

| Milestone | Description                                                 | Amount | Completion | Payment      |
|-----------|-------------------------------------------------------------|--------|------------|--------------|
| R1        | IPLD Schema and MVP implementation                          | 96000  | Done       | Invoice TODO |
| D2        | Golang implementation of Prolly Tree spec                   | 96000  | Done       | Invoice TODO |
| D3        | Golang IPLD indexer library                                 | 85800  | Done       | In-Review    |
| D4        | Example app to integrate with smart contracts               | 24000  | TODO       |              |
| R1        | pre-study and research on Prolly tree literature & projects | 39000  | Done       | Paid         |
| R2        | Golang IPLD indexer library                                 | 7500   | Done       | In-Review    |
| R3        | Research needs in the (mostly web3) ecosystem               | 9000   | TODO       |              |
| R4        | Research Applications and Feasibility                       | 9000   | TODO       |              |

**Comment by RangerMauve** [comment]
Also we're starting to see usage of the indexer on some projects already (not yet public). Personally I'm excited to bring it to more social data and knowledgebases.

The spec itself was used in another devgrant to have a rust version in the [Defluencer](https://github.com/Defluencer/rust-defluencer/blob/ab47fa7b3e69cb9d7a7eae8dc1584ea814d9eb21/defluencer/src/indexing/ordered_trees/prolly/tree.rs) project which is really cool to have. A useful follow-up would be to get the indexer spec implemented in there too so we can more easily use prolly trees in FVM use cases.

**Comment by RangerMauve** [comment]
Updated ticket

| Milestone | Description                                                 | Amount | Completion | Payment |
| --------- | ----------------------------------------------------------- | ------ |:---------- | ------- |
| D1        | IPLD Schema and MVP implementation                          | 96000  | Done       | Done    |
| D2        | Golang implementation of Prolly Tree spec                   | 96000  | Done       | Done    |
| D3        | Golang IPLD indexer library                                 | 85800  | Done       | Done    |
| D4        | Example app to integrate with smart contracts               | 24000  | Deploying  | TODO    |
| R1        | pre-study and research on Prolly tree literature & projects | 39000  | Done       | Done    |
| R2        | Golang IPLD indexer library                                 | 7500   | Done       | Done    |
| R3        | Research needs in the (mostly web3) ecosystem               | 9000   | Publishing | TODO    |
| R4        | Research Applications and Feasibility                       | 9000   | Publishing | TODO    |

**Comment by RangerMauve** [comment]
Link to live deployed oracle UI: http://www.lpmyblog.cn:88/

Oracle source code: https://github.com/KenCloud-Tech/prolly-tree-oracle

**Comment by ianconsolata** [comment]
HI @RangerMauve! I would love to check this out, but I can't seem to reach the oracle UI. It might be the hotel wifi I am on blocking port 88 -- would it be possible for you to deploy the UI at port 80?


Screenshot 2024-10-23 at 12 09 26 PM

**Comment by RangerMauve** [comment]
Looking into this now!

**Comment by taoshengshi** [comment]
> HI @RangerMauve! I would love to check this out, but I can't seem to reach the oracle UI. It might be the hotel wifi I am on blocking port 88 -- would it be possible for you to deploy the UI at port 80?
> 
> Screenshot 2024-10-23 at 12 09 26 PM


Hi @ianconsolata re-deploy here:
Prolly Tree Indexed Data Oracle for IPLD
https://dataoracle.gitdata.ai/

**Comment by taoshengshi** [comment]
Hi @ianconsolata Sorry that the devops engineer forgot to deploy the backend server totally as we doing domain name migration last time 😭 Now re-deploy the backend server and please check again.

**Comment by ianconsolata** [comment]
Hi @taoshengshi I tried again, but I am still getting the same errors as before. Is https://dataoracle.gitdata.ai/ still the correct url to try? Or do I maybe need to call a different command (such as CreateIndex) between Create and Put/Import?

**Comment by RangerMauve** [comment]
@ianconsolata When you have time could you review the post for R4?

https://github.com/RangerMauve/blog.mauve.moe/pull/3

**Comment by RangerMauve** [comment]
R3 published on medium.https://medium.com/@lendon.gertner/probabilistic-b-trees-in-peer-to-peer-databases-988cd4232621

**Comment by RangerMauve** [comment]
Updated ticket

| Milestone | Description                                                 | Amount | Completion | Payment |
| --------- | ----------------------------------------------------------- | ------ |:---------- | ------- |
| D1        | IPLD Schema and MVP implementation                          | 96000  | Done       | Done    |
| D2        | Golang implementation of Prolly Tree spec                   | 96000  | Done       | Done    |
| D3        | Golang IPLD indexer library                                 | 85800  | Done       | Done    |
| D4        | Example app to integrate with smart contracts               | 24000  | Final Review  | TODO    |
| R1        | pre-study and research on Prolly tree literature & projects | 39000  | Done       | Done    |
| R2        | Golang IPLD indexer library                                 | 7500   | Done       | Done    |
| R3        | Research needs in the (mostly web3) ecosystem               | 9000   | Published | TODO    |
| R4        | Research Applications and Feasibility                       | 9000   | Published | TODO    |

**Pull request merged**
