### PR TITLE
Open Grant Proposal: IPFS support in FFmpeg-based media players

### PR DESCRIPTION
**Pull request by markg85**
In summary, this proposal asks for funding to add:

1. FFmpeg to natively support `ipfs://bafy...` and `ipns://bafy...` directly usable from within ffmpeg.
2. MPV to natively support the `ipfs` and `ipns` protocols (it depends on ffmpeg).
3. VLC to natively support the `ipfs` and `ipns` protocols (it could depend on the ffmpeg change, it could also be implemented in their module concept).
4. KODI to natively support the `ipfs` and `ipns` protocols (it depends on ffmpeg) through the various ways it can play web-based content.
5. A KODI addon to allow adding a `ipfs://bafy...` and `ipns://bafy...` folder as video folder and play content from it.

### CODE REVIEW

**Comment by realChainLife** [comment]
Hi @markg85 thank you for your proposal. We would like to fund the work in this proposal. Please email devgrants@fil.org tp discuss next steps.

**Comment by markg85** [comment]
Hi @realChainLife, thank you for the response and the great news! A mail has been send. I'm looking forward to discuss those next steps!

**Comment by vans163** [comment]
+1 to make it possible to upload to IPFS as well, using ipfs://.. as output from a transcode for example.

**Comment by markg85** [comment]
Hi @vans163 

While that is a nice feature, it's way more complicated then it might look at first glance.
The IPFS support in ffmpeg is making use of a gateway (preferably a local one). A gateway is readonly by design and therefore doesn't allow to upload anything.

What you're asking would be deeper interaction with IPFS from the ffmpeg side. Interaction that isn't possible via the gateway. One could consider interacting with one of the other IPFS API options (i think it has websockets too?). That could work but is far outside the scope of this project. Do note that ffmpeg **must** know the local node (or writable API endpoint) in this case. In the current implementation it only needs to know a gateway, a local node is not required (but is advised).

I think this is best left to other commands outside of ffmpeg.

**Comment by vans163** [comment]
> Hi @vans163
> 
> While that is a nice feature, it's way more complicated then it might look at first glance. The IPFS support in ffmpeg is making use of a gateway (preferably a local one). A gateway is readonly by design and therefore doesn't allow to upload anything.
> 
> What you're asking would be deeper interaction with IPFS from the ffmpeg side. Interaction that isn't possible via the gateway. One could consider interacting with one of the other IPFS API options (i think it has websockets too?). That could work but is far outside the scope of this project. Do note that ffmpeg **must** know the local node (or writable API endpoint) in this case. In the current implementation it only needs to know a gateway, a local node is not required (but is advised).
> 
> I think this is best left to other commands outside of ffmpeg.

But if using a gateway cant you just pass the URL and ffmpeg will fetch out the gateway?

Yea just using the API perhaps similar to how HTTP output is done.

```
ffmpeg -stream_loop -1 -i /video/Notld1968Restoration.mp4 -c:v libx264 -preset slow -threads 4 -g 30 -keyint_min 30 -movflags +faststart -b:v 2600k -f mp4 -ipfs http://127.0.0.1:5001/
```
example, just indicate `-ipfs` and the http(s) protocol + ip:port to indicate where the IPFS node is. The command above once finished will output the IPFS hash.

**Comment by vans163** [comment]
Nice to see this land in FFMPEG 5.1! Great job.
https://github.com/FFmpeg/FFmpeg/blob/master/Changelog

**Comment by alexandervlpl** [comment]
This is great, can't wait to see IPFS in Android VLC!

**Comment by markg85** [comment]
> This is great, can't wait to see IPFS in Android VLC!

Thank you for your optimism :)

In terms of this grant specifically, we (Protocol Labs and I) abandoned it essentially after ffmpeg got merged. It also landed in mpv. I started working for PL and instead implemented ipfs in curl (which landed too but was a monstrous task). 

There is no effort on my side to get IPFS in VLC or KODI anymore (the two remaining ones in this grant).
VLC was contacted about IPFS interest and was having questions about it's usefulness but wasn't against it.
KODI was also contacted, they did not see why it would be any useful.

The hard part in this isn't even getting `ipfs://...` working. Heck, in VLCs case, i made a [hacky patch](https://code.videolan.org/markg85/vlc-android-ipfs/-/compare/master...master?from_project_id=36) just to get it working years ago already in a mere few hours. It's explaining them why having it working in their app is a nice feature to have. That explaining is what takes the vast amount of time! Especially in large projects with lots of people (and therefore opinions) where some will be vocally against it. You have to listen to them, listen to their concerns, staying polite even though you might feel attacked and work on a solution. Usually having working code already to show does help the discussion!

Anyhow, VLC and KODI are up for grabs for someone else to take on.

**Pull request closed without merging**
