### PR TITLE
[Open Grants Proposal] - OpenRegistry DevGrant Proposal

### PR DESCRIPTION
**Pull request by jay-dee7**
# Description
Hello Team :)
We're building a decentralised container registry, which is fully compliant with the OCI Distribution Specification. The specification provides similar capabilities as that of the Docker Registry HTTP API V2 protocol and more. We recently received certification from Open Containers Initiative organisation, 
more detail about that can be found here: https://conformance.opencontainers.org/#openregistry 

We'd love to apply for IPFS Open DevGrants program so that we can continue to support our development and engineering efforts.

Signed-off-by: jay-dee7 <jasdeepsingh.uppal@gmail.com>

### CODE REVIEW

**Comment by jay-dee7** [comment]
@realChainLife can we please get any update on this PR?

**Comment by ErinOCon** [comment]
Hi @jay-dee7, thank you for your patience as this grant is reviewed! We would like to move forward with the first milestones of your project! Upon completion of these milestones, we can consider future support opportunities. For next steps, can the first two milestones be broken down into three to four milestones? Each milestone should include a description, payment amount, and estimated timeframe. 

For future support opportunities beyond the first two milestones, we would be interested to learn if you intend to write a new implementation of IPFS (since, as of right now, IPFS does not have a java implementation).

**Comment by guacamole** [comment]
Hey @ErinOCon, thanks a lot for reviewing and getting back to us. We can totally split the milestones into smaller milestones starting from the 3rd milestone. Would you be open to getting on a call and discuss this in detail? or should we keep it in comments here?

Our team doesn't have expertise in Java as we use Go as our primary backend language. So the java implementation might not be our forte per se.

**Comment by ErinOCon** [comment]
Hi @guacamole. happy to continue the discussion over a call call! I will send you calendar details by email.

**Comment by ErinOCon** [comment]
Hi @guacamole, we are please to proceed with the approval of milestones 3 and 4 of your proposal. I have sent program details and next steps to [jasdeepsingh.uppal@gmail.com](mailto:jasdeepsingh.uppal@gmail.com). Please let me know if you have any questions or would like to discuss further.

**Comment by jay-dee7** [comment]
Thanks for sending the details @ErinOCon over email. We'll follow up ASAP

**Comment by ErinOCon** [comment]
@jay-dee7 @guacamole I have sent a reply to your inquiries by email, but it looks like it may not have gone through. Please let me know if you have trouble receiving the message.

**Comment by jay-dee7** [comment]
Hey @ErinOCon we actually did not receive the email. Can you please resend it or forward it to `team@openregistry.dev`

**Comment by ErinOCon** [comment]
Hi @jay-dee7, thank you for letting me know. I have sent the email to the provided address.

**Comment by ErinOCon** [comment]
Hi @jay-dee7, thank you for your response. I have started a new thread.

**Pull request merged**
